export const COUNTRIES = [
    { code: 'USA', name: 'United States', flag: '🇺🇸' },
    { code: 'CHN', name: 'China', flag: '🇨🇳' },
    { code: 'JPN', name: 'Japan', flag: '🇯🇵' },
    { code: 'DEU', name: 'Germany', flag: '🇩🇪' },
    { code: 'RUS', name: 'Russia', flag: '🇷🇺' },
    { code: 'AUS', name: 'Australia', flag: '🇦🇺' },
    { code: 'IND', name: 'India', flag: '🇮🇳' },
    { code: 'CAN', name: 'Canada', flag: '🇨🇦' },
    { code: 'BRA', name: 'Brazil', flag: '🇧🇷' },
    { code: 'ITA', name: 'Italy', flag: '🇮🇹' },
    { code: 'SLV', name: 'El Salvador', flag: '🇸🇻' },
];
export const CONSOLES = [
    {
        id: 'game-boy',
        name: 'Game Boy',
        referencePriceUsd: 100,
        imagePath: 'images/gameboy.png',
        imageWidth: 640,
        imageHeight: 776,
    },
    {
        id: 'atari-2600',
        name: 'Atari 2600',
        referencePriceUsd: 100,
        imagePath: 'images/atari2600.png',
        imageWidth: 800,
        imageHeight: 467,
    },
    {
        id: 'nes',
        name: 'NES',
        referencePriceUsd: 150,
        imagePath: 'images/nes.png',
        imageWidth: 800,
        imageHeight: 558,
    },
    {
        id: 'snes',
        name: 'SNES',
        referencePriceUsd: 200,
        imagePath: 'images/snes.png',
        imageWidth: 800,
        imageHeight: 416,
    },
    {
        id: 'playstation',
        name: 'PlayStation',
        referencePriceUsd: 80,
        imagePath: 'images/playstation.png',
        imageWidth: 800,
        imageHeight: 348,
    },
    {
        id: 'nintendo-64',
        name: 'Nintendo 64',
        referencePriceUsd: 300,
        imagePath: 'images/n64.png',
        imageWidth: 800,
        imageHeight: 431,
    },
    {
        id: 'xbox',
        name: 'Xbox',
        referencePriceUsd: 150,
        imagePath: 'images/xbox.png',
        imageWidth: 728,
        imageHeight: 335,
    },
    {
        id: 'gamecube',
        name: 'GameCube',
        referencePriceUsd: 180,
        imagePath: 'images/gamecube.png',
        imageWidth: 800,
        imageHeight: 449,
    },
];
export const MAXIMUM_BITCOIN_SUPPLY = 21000000;
